// mock apicaller with response text for 5 articles

(function(exports) {
    function MockApiCaller(date) {
    this.responseText = '{"response":{"status":"ok","userTier":"developer","total":69914,"startIndex":1,"pageSize":10,"currentPage":1,"pages":6992,"orderBy":"relevance","results":[{"id":"books/2019/oct/03/the-10-biggest-books-of-autumn-2019","type":"article","sectionId":"books","sectionName":"Books","webPublicationDate":"2019-10-03T05:00:39Z","webTitle":"The 10 biggest books of autumn 2019","webUrl":"https://www.theguardian.com/books/2019/oct/03/the-10-biggest-books-of-autumn-2019","apiUrl":"https://content.guardianapis.com/books/2019/oct/03/the-10-biggest-books-of-autumn-2019","isHosted":false,"pillarId":"pillar/arts","pillarName":"Arts"},{"id":"clarks-curators/2019/sep/17/10-timeless-fashion-trends-that-never-date","type":"article","sectionId":"clarks-curators","sectionName":"Clarks curators","webPublicationDate":"2019-09-17T15:05:57Z","webTitle":"10 timeless fashion trends that never date","webUrl":"https://www.theguardian.com/clarks-curators/2019/sep/17/10-timeless-fashion-trends-that-never-date","apiUrl":"https://content.guardianapis.com/clarks-curators/2019/sep/17/10-timeless-fashion-trends-that-never-date","isHosted":false},{"id":"culture/2019/jul/22/comic-con-2019-10-biggest-surprises-marvel","type":"article","sectionId":"culture","sectionName":"Culture","webPublicationDate":"2019-07-22T15:41:58Z","webTitle":"Thor! Blade! Picard! The 10 biggest surprises from Comic-Con 2019","webUrl":"https://www.theguardian.com/culture/2019/jul/22/comic-con-2019-10-biggest-surprises-marvel","apiUrl":"https://content.guardianapis.com/culture/2019/jul/22/comic-con-2019-10-biggest-surprises-marvel","isHosted":false,"pillarId":"pillar/arts","pillarName":"Arts"},{"id":"stage/2019/aug/13/edinburgh-festival-2019-the-10-best-jokes","type":"article","sectionId":"stage","sectionName":"Stage","webPublicationDate":"2019-08-13T05:29:18Z","webTitle":"Edinburgh festival 2019: the 10 best jokes","webUrl":"https://www.theguardian.com/stage/2019/aug/13/edinburgh-festival-2019-the-10-best-jokes","apiUrl":"https://content.guardianapis.com/stage/2019/aug/13/edinburgh-festival-2019-the-10-best-jokes","isHosted":false,"pillarId":"pillar/arts","pillarName":"Arts"},{"id":"stage/2019/jun/24/edinburgh-fringe-2019-10-essential-shows-reviewed","type":"article","sectionId":"stage","sectionName":"Stage","webPublicationDate":"2019-06-24T05:00:07Z","webTitle":"Edinburgh fringe 2019: 10 essential shows","webUrl":"https://www.theguardian.com/stage/2019/jun/24/edinburgh-fringe-2019-10-essential-shows-reviewed","apiUrl":"https://content.guardianapis.com/stage/2019/jun/24/edinburgh-fringe-2019-10-essential-shows-reviewed","isHosted":false,"pillarId":"pillar/arts","pillarName":"Arts"}]}}';
    }

    MockApiCaller.prototype.getGuardian = function() {
        var data = JSON.parse(this.responseText);
        return data;
    };

    exports.MockApiCaller = MockApiCaller;
})(this);