env:
  jest: true
  browser: true
  commonjs: true
  es2021: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: 8
rules:
  strict: off
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
