const data = {
  response: {
    status: 'ok',
    userTier: 'developer',
    total: 7167,
    startIndex: 1,
    pageSize: 10,
    currentPage: 1,
    pages: 717,
    orderBy: 'newest',
    results: [
      {
        id: 'politics/live/2022/nov/23/scottish-independence-referendum-supreme-court-scotland-pmqs-sunak-starmer-uk-politics-live-latest-news',
        type: 'liveblog',
        sectionId: 'politics',
        sectionName: 'Politics',
        webPublicationDate: '2022-11-23T20:59:15Z',
        webTitle: 'Hundreds gather at Holyrood after Scottish government loses independence referendum case – UK politics live',
        webUrl: 'https://www.theguardian.com/politics/live/2022/nov/23/scottish-independence-referendum-supreme-court-scotland-pmqs-sunak-starmer-uk-politics-live-latest-news',
        apiUrl: 'https://content.guardianapis.com/politics/live/2022/nov/23/scottish-independence-referendum-supreme-court-scotland-pmqs-sunak-starmer-uk-politics-live-latest-news',
        fields: {
          headline: 'Hundreds gather at Holyrood after Scottish government loses independence referendum case – UK politics live',
          byline: 'Nadeem Badshah (now) ,Andrew Sparrow (earlier)',
          thumbnail: 'https://media.guim.co.uk/661ebbad21639a7dcdab4d641b0ea3452b3771de/0_159_5472_3283/500.jpg',
        },
        isHosted: false,
        pillarId: 'pillar/news',
        pillarName: 'News',
      },
      {
        id: 'commentisfree/2022/nov/21/qatar-world-cup-british-double-standards-anger-gifts-property-arms-deals',
        type: 'article',
        sectionId: 'commentisfree',
        sectionName: 'Opinion',
        webPublicationDate: '2022-11-21T06:00:47Z',
        webTitle: 'It’s not just Qatar hoping we now ‘put politics aside’. It’s the hypocritical west, too | Nesrine Malik',
        webUrl: 'https://www.theguardian.com/commentisfree/2022/nov/21/qatar-world-cup-british-double-standards-anger-gifts-property-arms-deals',
        apiUrl: 'https://content.guardianapis.com/commentisfree/2022/nov/21/qatar-world-cup-british-double-standards-anger-gifts-property-arms-deals',
        fields: {
          headline: 'It’s not just Qatar hoping we now ‘put politics aside’. It’s the hypocritical west, too',
          byline: 'Nesrine Malik',
          thumbnail: 'https://media.guim.co.uk/41b4ac8de2f0d59c93c54cb0983e44928194df38/0_117_5439_3263/500.jpg',
        },
        isHosted: false,
        pillarId: 'pillar/opinion',
        pillarName: 'Opinion',
      },
      {
        id: 'australia-news/2022/nov/20/daniel-andrews-rejects-americanisation-of-politics-after-mps-controversial-speech',
        type: 'article',
        sectionId: 'australia-news',
        sectionName: 'Australia news',
        webPublicationDate: '2022-11-20T05:22:56Z',
        webTitle: 'Daniel Andrews rejects ‘Americanisation’ of politics after MP’s controversial speech ',
        webUrl: 'https://www.theguardian.com/australia-news/2022/nov/20/daniel-andrews-rejects-americanisation-of-politics-after-mps-controversial-speech',
        apiUrl: 'https://content.guardianapis.com/australia-news/2022/nov/20/daniel-andrews-rejects-americanisation-of-politics-after-mps-controversial-speech',
        fields: {
          headline: 'Daniel Andrews rejects ‘Americanisation’ of politics after MP’s controversial speech ',
          byline: 'Benita Kolovos',
          thumbnail: 'https://media.guim.co.uk/62383d2f1eaf618beac25ea6b90da4e5289f7fc1/0_179_5417_3252/500.jpg',
        },
        isHosted: false,
        pillarId: 'pillar/news',
        pillarName: 'News',
      },
      {
        id: 'politics/2022/nov/19/keir-starmer-i-will-abolish-house-of-lords-to-restore-trust-in-politics',
        type: 'article',
        sectionId: 'politics',
        sectionName: 'Politics',
        webPublicationDate: '2022-11-19T19:30:05Z',
        webTitle: 'Keir Starmer: I will abolish House of Lords to ‘restore trust in politics’',
        webUrl: 'https://www.theguardian.com/politics/2022/nov/19/keir-starmer-i-will-abolish-house-of-lords-to-restore-trust-in-politics',
        apiUrl: 'https://content.guardianapis.com/politics/2022/nov/19/keir-starmer-i-will-abolish-house-of-lords-to-restore-trust-in-politics',
        fields: {
          headline: 'Keir Starmer: I will abolish House of Lords to ‘restore trust in politics’',
          byline: 'Michael Savage Policy editor',
          thumbnail: 'https://media.guim.co.uk/259fa2db1009cb1959e7a692e541519119dd97d5/59_254_3474_2084/500.jpg',
        },
        isHosted: false,
        pillarId: 'pillar/news',
        pillarName: 'News',
      },
      {
        id: 'australia-news/2022/nov/19/the-cost-of-losing-the-politics-of-pokies-in-the-gaming-machine-capital-of-australia',
        type: 'article',
        sectionId: 'australia-news',
        sectionName: 'Australia news',
        webPublicationDate: '2022-11-18T14:00:32Z',
        webTitle: 'The cost of losing the politics of pokies in the gaming machine capital of Australia',
        webUrl: 'https://www.theguardian.com/australia-news/2022/nov/19/the-cost-of-losing-the-politics-of-pokies-in-the-gaming-machine-capital-of-australia',
        apiUrl: 'https://content.guardianapis.com/australia-news/2022/nov/19/the-cost-of-losing-the-politics-of-pokies-in-the-gaming-machine-capital-of-australia',
        fields: {
          headline: 'The cost of losing the politics of pokies in the gaming machine capital of Australia',
          byline: 'Michael McGowan and Josh Nicholas',
          thumbnail: 'https://media.guim.co.uk/de067445f782042c396ce43018d612ecb7bc1057/0_0_3500_2102/500.jpg',
        },
        isHosted: false,
        pillarId: 'pillar/news',
        pillarName: 'News',
      },
      {
        id: 'australia-news/2022/nov/17/afternoon-update-mining-industrys-windfall-tax-threat-victorias-messy-politics-and-a-christmas-gift-guide',
        type: 'article',
        sectionId: 'australia-news',
        sectionName: 'Australia news',
        webPublicationDate: '2022-11-17T06:19:37Z',
        webTitle: 'Afternoon Update: mining industry’s windfall tax threat; Victoria’s messy politics; and a Christmas gift guide',
        webUrl: 'https://www.theguardian.com/australia-news/2022/nov/17/afternoon-update-mining-industrys-windfall-tax-threat-victorias-messy-politics-and-a-christmas-gift-guide',
        apiUrl: 'https://content.guardianapis.com/australia-news/2022/nov/17/afternoon-update-mining-industrys-windfall-tax-threat-victorias-messy-politics-and-a-christmas-gift-guide',
        fields: {
          headline: 'Afternoon Update: mining industry’s windfall tax threat; Victoria’s messy politics; and a Christmas gift guide',
          byline: 'Antoun Issa',
          thumbnail: 'https://media.guim.co.uk/fd3552870c4835f1544c44fc5b5c6fca6b9b4a0f/0_107_7371_4425/500.jpg',
        },
        isHosted: false,
        pillarId: 'pillar/news',
        pillarName: 'News',
      },
      {
        id: 'us-news/2022/nov/16/qa-what-does-a-split-congress-mean-for-us-politics',
        type: 'article',
        sectionId: 'us-news',
        sectionName: 'US news',
        webPublicationDate: '2022-11-16T23:56:29Z',
        webTitle: 'Q&A: what does a split Congress mean for US politics?',
        webUrl: 'https://www.theguardian.com/us-news/2022/nov/16/qa-what-does-a-split-congress-mean-for-us-politics',
        apiUrl: 'https://content.guardianapis.com/us-news/2022/nov/16/qa-what-does-a-split-congress-mean-for-us-politics',
        fields: {
          headline: 'Q&A: what does a split Congress mean for US politics?',
          byline: 'Joan E Greve',
          thumbnail: 'https://media.guim.co.uk/834590d49b78a0543fa338577b9fc15c5fda251e/0_0_3500_2100/500.jpg',
        },
        isHosted: false,
        pillarId: 'pillar/news',
        pillarName: 'News',
      },
      {
        id: 'artanddesign/2022/nov/14/elizabeth-price-underfoot-hunterian-art-gallery-review',
        type: 'article',
        sectionId: 'artanddesign',
        sectionName: 'Art and design',
        webPublicationDate: '2022-11-14T14:09:15Z',
        webTitle: 'Elizabeth Price review – carpet-focused show is a rich weave of politics and passion',
        webUrl: 'https://www.theguardian.com/artanddesign/2022/nov/14/elizabeth-price-underfoot-hunterian-art-gallery-review',
        apiUrl: 'https://content.guardianapis.com/artanddesign/2022/nov/14/elizabeth-price-underfoot-hunterian-art-gallery-review',
        fields: {
          headline: 'Elizabeth Price review – carpet-focused show is a rich weave of politics and passion',
          byline: 'Lisette May Monroe',
          thumbnail: 'https://media.guim.co.uk/92fbe6f6085efaf617b75826819f7a13a8b8096e/0_60_2410_1446/500.jpg',
        },
        isHosted: false,
        pillarId: 'pillar/arts',
        pillarName: 'Arts',
      },
      {
        id: 'australia-news/2022/nov/14/australias-gambling-addiction-can-politics-finally-stop-the-money-wheel-turning',
        type: 'article',
        sectionId: 'australia-news',
        sectionName: 'Australia news',
        webPublicationDate: '2022-11-13T16:30:15Z',
        webTitle: 'Australia’s gambling addiction: can politics finally stop the money wheel turning?',
        webUrl: 'https://www.theguardian.com/australia-news/2022/nov/14/australias-gambling-addiction-can-politics-finally-stop-the-money-wheel-turning',
        apiUrl: 'https://content.guardianapis.com/australia-news/2022/nov/14/australias-gambling-addiction-can-politics-finally-stop-the-money-wheel-turning',
        fields: {
          headline: 'Australia’s gambling addiction: can politics finally stop the money wheel turning?',
          byline: 'Stephanie Convery, Josh Nicholas and Andy Ball',
          thumbnail: 'https://media.guim.co.uk/9d110604f47286a0d19fd054f0e32d06af7b5e08/0_171_4724_2835/500.jpg',
        },
        isHosted: false,
        pillarId: 'pillar/news',
        pillarName: 'News',
      },
      {
        id: 'commentisfree/2022/nov/13/disgraced-tory-mps-shame-our-politics-will-rishi-sunak-keep-promise-clean-up-house',
        type: 'article',
        sectionId: 'commentisfree',
        sectionName: 'Opinion',
        webPublicationDate: '2022-11-13T09:00:06Z',
        webTitle: 'As disgraced Tory MPs shame politics, will Rishi Sunak keep his promise to clean up the house? | Andrew Rawnsley',
        webUrl: 'https://www.theguardian.com/commentisfree/2022/nov/13/disgraced-tory-mps-shame-our-politics-will-rishi-sunak-keep-promise-clean-up-house',
        apiUrl: 'https://content.guardianapis.com/commentisfree/2022/nov/13/disgraced-tory-mps-shame-our-politics-will-rishi-sunak-keep-promise-clean-up-house',
        fields: {
          headline: 'As disgraced Tory MPs shame politics, will Rishi Sunak keep his promise to clean up the house?',
          byline: 'Andrew Rawnsley',
          thumbnail: 'https://media.guim.co.uk/ab01ac8275d36f173290a0e001f9c19e34060c79/0_174_5230_3138/500.jpg',
        },
        isHosted: false,
        pillarId: 'pillar/opinion',
        pillarName: 'Opinion',
      },
    ],
  }
}

module.exports = data;