var testCreateArticleList = (function() {
  var articleListDouble = new ArticleListDouble()
  var articleListViewDouble = new ArticleListViewDouble(articleListDouble)
  var requestDouble = new XMLHttpRequestDouble()
  var articleListController = new ArticleListController(articleListDouble, articleListViewDouble, requestDouble)
  articleListController.createArticleList()
  assert.isTrue(articleListController._articleList.articles().length === 2)
  assert.isTrue(articleListController._articleList.addArticleCallCount === 2)
  assert.isTrue(articleListController._request.openCallCount === 1)
  assert.isTrue(articleListController._request.sendCallCount === 1)
  // assert.isTrue(articleListController._request.onloadCallCount === 1)
})()

testRenderArticleList = (function() {
  var articleListDouble = new ArticleListDouble()
  var articleListViewDouble = new ArticleListViewDouble(articleListDouble)
  var articleListController = new ArticleListController(articleListDouble, articleListViewDouble)
  articleListController.renderArticleList()
  assert.isTrue(document.getElementById("article-list").innerHTML === "<li>Title</li><li>Title</li>")
  assert.isTrue(articleListViewDouble.htmlStringCallCount === 1)
  assert.isTrue(articleListViewDouble.updateArticleListCallCount === 1)
})()
