(function (exports) {
  let listView

  function displayTitleAndSummary () {
    console.log('displayTitleAndSummary')
    let articleList = new ArticleList
    let articleOne = new Article('He spoke out about the Wuhan virus.', 'apiUrl', `As people across China mourned the death of a whistleblower doctor in an almost unprecedented outpouring of grief and anger on Thursday, little did they know that another truth-teller of the coronavirus outbreak was being silenced, according to friends and family. Chen Qiushi, a citizen journalist who had been doing critical reporting from Wuhan, the central Chinese city at the epicenter of the outbreak, went missing on Thursday evening, just as hundreds of thousands of people in China began demanding freedom of speech online. Li Wenliang, a 34-year-old ophthalmologist in Wuhan, died of the same virus he had tried to warn others about early on in the outbreak, which has now killed more than 800 people mostly in mainland China. Rather than being listened to, he was punished by the police for "spreading rumors," and later contracted the virus from a patient. Li's passing ignited a storm of outrage across China, with an intensity and scope rarely seen in its tightly-controled online sphere. People called for an official apology from the government and flooded social media with the hashtag "I want freedom of speech," a fundamental right supposedly protected under the country's constitution.`, "I am the first summary about the doctor.")
    let articleTwo = new Article('Iowa conspiracy theories ', 'apiUrl', `Almost a year before the Iowa caucuses, a top US cybersecurity official said fears about foreign meddling in the 2020 election were the one thing that kept him up at night. But if this week's debacle in the first vote of the Democratic presidential primaries is anything to go by, another formidable threat to American democracy lies much closer to home. As the hours ticked by Monday night with no sign of results out of Iowa, a lack of information from election officials left a void filled by a torrent of American-made misinformation, conspiracy theories about what went wrong, and claims of vote-fixing. There is no sign that external interference played any role in the meltdown of the Iowa Democratic Party's reporting system (some of the blame lies with the apparent failure of an app). In fact, the work that was done to cast doubt over the democratic process -- efforts typically pinned on foreign adversaries and bad actors -- was being done by Americans themselves. Russia, backed by an army of trolls and bolstered by hacks, in 2016 showed the world that hybrid information warfare could influence an election. One element of Moscow's efforts focused on sowing discord through a coordinated disinformation campaign, according to special counsel Robert Mueller's report. Another involved a "hack and leak" -- including the computer hacking of the Clinton campaign and the leaking of embarrassing emails. The aim of both strategies was not only to discourage voting for then-candidate Hilary Clinton, but to make Americans feel like their vote didn't matter and dissuade them from voting altogether. The US intelligence community anticipates foreign actors will try to use the same tactics again in 2020, and there are already signs of interference from Russia (Moscow denies all claims of meddling). Late last year, Congress approved $425 million in election security funding, as part of an effort to safeguard against interference. But, with nine months still to go, Iowa is worrisome evidence that the challenge is also internal: misinformation is just as likely to come from inside the US as from outside, experts say.`, "I am the summary about Iowa.")
    articleList.add(articleOne)
    articleList.add(articleTwo)
    listView = new ListView(articleList)
    expect(listView.display()).toInclude(articleOne.title)
    expect(listView.display()).toInclude(articleTwo.title)
    expect(listView.display()).notToInclude(articleOne.body)
    expect(listView.display()).notToInclude(articleTwo.body)
    expect(listView.display()).toInclude(articleOne.summary)
    expect(listView.display()).toInclude(articleTwo.summary)
  }

  displayTitleAndSummary()
})(this)