var headlines = new Headlines({
  "response":{
    "status":"ok",
    "userTier":"developer",
    "total":104,
    "startIndex":1,
    "pageSize":10,
    "currentPage":1,
    "pages":11,
    "orderBy":"newest",
    "results":[
      {"id":"football/live/2020/jan/12/brighton-v-arsenal-womens-super-league-live",
      "type":"liveblog",
      "sectionId":"football",
      "sectionName":"Football",
      "webPublicationDate":"2020-01-12T13:53:17Z",
      "webTitle":"Brighton v Arsenal: Women's Super League – live!",
      "webUrl":"https://www.theguardian.com/football/live/2020/jan/12/brighton-v-arsenal-womens-super-league-live","apiUrl":"https://content.guardianapis.com/football/live/2020/jan/12/brighton-v-arsenal-womens-super-league-live",
      "isHosted":false,
      "pillarId":"pillar/sport",
      "pillarName":"Sport"},
      {"id":"football/live/2020/jan/12/bournemouth-v-watford-premier-league-live",
      "type":"liveblog",
      "sectionId":"football",
      "sectionName":"Football",
      "webPublicationDate":"2020-01-12T13:51:24Z",
      "webTitle":"Bournemouth v Watford: Premier League – live!","webUrl":"https://www.theguardian.com/football/live/2020/jan/12/bournemouth-v-watford-premier-league-live",
      "apiUrl":"https://content.guardianapis.com/football/live/2020/jan/12/bournemouth-v-watford-premier-league-live","isHosted":false,"pillarId":"pillar/sport","pillarName":"Sport"},
      {"id":"us-news/2020/jan/12/donald-trump-impeachment-nancy-pelosi-articles-senate-trial",
      "type":"article",
      "sectionId":"us-news",
      "sectionName":"US news","webPublicationDate":"2020-01-12T13:25:32Z",
      "webTitle":"Impeachment: Pelosi prepares to transmit articles as Trump fumes","webUrl":"https://www.theguardian.com/us-news/2020/jan/12/donald-trump-impeachment-nancy-pelosi-articles-senate-trial","apiUrl":"https://content.guardianapis.com/us-news/2020/jan/12/donald-trump-impeachment-nancy-pelosi-articles-senate-trial","isHosted":false,
      "pillarId":"pillar/news",
      "pillarName":"News"},
      {"id":"politics/2020/jan/12/festival-of-brexit-boss-120m-event-will-prove-cynics-wrong-martin-green","type":"article","sectionId":"politics",
      "sectionName":"Politics",
      "webPublicationDate":"2020-01-12T13:24:50Z",
      "webTitle":"'Festival of Brexit' boss says £120m event will prove the cynics wrong","webUrl":"https://www.theguardian.com/politics/2020/jan/12/festival-of-brexit-boss-120m-event-will-prove-cynics-wrong-martin-green","apiUrl":"https://content.guardianapis.com/politics/2020/jan/12/festival-of-brexit-boss-120m-event-will-prove-cynics-wrong-martin-green",
      "isHosted":false,
      "pillarId":"pillar/news","pillarName":"News"},{"id":"music/2020/jan/12/hatsune-miku-review-london-02-academy-brixton-london",
      "type":"article",
      "sectionId":"music",
      "sectionName":"Music","webPublicationDate":"2020-01-12T13:23:33Z",
      "webTitle":"Hatsune Miku review – hologram star fires up the glowsticks",
      "webUrl":"https://www.theguardian.com/music/2020/jan/12/hatsune-miku-review-london-02-academy-brixton-london",
      "apiUrl":"https://content.guardianapis.com/music/2020/jan/12/hatsune-miku-review-london-02-academy-brixton-london","isHosted":false,
      "pillarId":"pillar/arts",
      "pillarName":"Arts"},
      {"id":"world/2020/jan/12/iran-riot-police-anti-government-backlash-ukraine",
      "type":"article",
      "sectionId":"world",
      "sectionName":"World news",
      "webPublicationDate":"2020-01-12T13:13:06Z",
      "webTitle":"Iran deploys riot police as anti-government backlash grows",
      "webUrl":"https://www.theguardian.com/world/2020/jan/12/iran-riot-police-anti-government-backlash-ukraine",
      "apiUrl":"https://content.guardianapis.com/world/2020/jan/12/iran-riot-police-anti-government-backlash-ukraine",
      "isHosted":false,
      "pillarId":"pillar/news",
      "pillarName":"News"},
      {"id":"lifeandstyle/2020/jan/12/how-to-escape-your-phone-and-other-life-hacks",
      "type":"article",
      "sectionId":"lifeandstyle","sectionName":"Life and style","webPublicationDate":"2020-01-12T13:00:36Z",
      "webTitle":"How to escape your phone and other life hacks",
      "webUrl":"https://www.theguardian.com/lifeandstyle/2020/jan/12/how-to-escape-your-phone-and-other-life-hacks",
      "apiUrl":"https://content.guardianapis.com/lifeandstyle/2020/jan/12/how-to-escape-your-phone-and-other-life-hacks",
      "isHosted":false,
      "pillarId":"pillar/lifestyle","pillarName":"Lifestyle"},
      {"id":"music/2020/jan/12/field-music-making-a-new-world-review-first-world-war","type":"article","sectionId":"music",
      "sectionName":"Music",
      "webPublicationDate":"2020-01-12T13:00:35Z",
      "webTitle":"Field Music: Making a New World review – a concept stronger than the songs","webUrl":"https://www.theguardian.com/music/2020/jan/12/field-music-making-a-new-world-review-first-world-war",
      "apiUrl":"https://content.guardianapis.com/music/2020/jan/12/field-music-making-a-new-world-review-first-world-war",
      "isHosted":false,
      "pillarId":"pillar/arts",
      "pillarName":"Arts"},
      {"id":"science/2020/jan/12/how-scientists-are-coping-with-environmental-grief",
      "type":"article",
      "sectionId":"science",
      "sectionName":"Science",
      "webPublicationDate":"2020-01-12T13:00:35Z",
      "webTitle":"How scientists are coping with ‘ecological grief’",
      "webUrl":"https://www.theguardian.com/science/2020/jan/12/how-scientists-are-coping-with-environmental-grief",
      "apiUrl":"https://content.guardianapis.com/science/2020/jan/12/how-scientists-are-coping-with-environmental-grief",
      "isHosted":false,
      "pillarId":"pillar/news",
      "pillarName":"News"},
      {"id":"books/2020/jan/12/this-mournable-body-by-tsitsi-dangarembga-review",
      "type":"article",
      "sectionId":"books",
      "sectionName":"Books",
      "webPublicationDate":"2020-01-12T13:00:35Z",
      "webTitle":"This Mournable Body by Tsitsi Dangarembga review – life on the precipice",
      "webUrl":"https://www.theguardian.com/books/2020/jan/12/this-mournable-body-by-tsitsi-dangarembga-review",
      "apiUrl":"https://content.guardianapis.com/books/2020/jan/12/this-mournable-body-by-tsitsi-dangarembga-review",
      "isHosted":false,
      "pillarId":"pillar/arts",
      "pillarName":"Arts"}]}})

function separateHeadlines() {
  assert.isTrue(headlines.individualHeadlines()[0] === "http://news-summary-api.herokuapp.com/guardian?apiRequestUrl=http://content.guardianapis.com/football/live/2020/jan/12/brighton-v-arsenal-womens-super-league-live?show-fields=body")
}
separateHeadlines();
