const testApiResult = {
  "response": {
    "status":"ok",
    "userTier":"developer",
    "total":2201657,
    "startIndex":1,"pageSize":10,
    "currentPage":1,
    "pages":220166,
    "orderBy":"newest",
    "results": [
      {
        "id":"football/live/2020/jun/27/aston-villa-v-wolves-premier-league-live",
        "type":"liveblog",
        "sectionId":"football",
        "sectionName":"Football",
        "webPublicationDate":"2020-06-27T11:28:22Z",
        "webTitle":"Aston Villa v Wolves: Premier League – live!",
        "webUrl":"https://www.theguardian.com/football/live/2020/jun/27/aston-villa-v-wolves-premier-league-live",
        "apiUrl":"https://content.guardianapis.com/football/live/2020/jun/27/aston-villa-v-wolves-premier-league-live",
        "isHosted":false,
        "pillarId":"pillar/sport",
        "pillarName":"Sport"
      },
      {
        "id":"stage/2020/mar/17/hottest-front-room-seats-the-best-theatre-and-dance-to-watch-online",
        "type":"article",
        "sectionId":"stage",
        "sectionName":"Stage",
        "webPublicationDate":"2020-06-27T11:24:58Z",
        "webTitle":"Hottest front-room seats: the best theatre and dance to watch online",
        "webUrl":"https://www.theguardian.com/stage/2020/mar/17/hottest-front-room-seats-the-best-theatre-and-dance-to-watch-online",
        "apiUrl":"https://content.guardianapis.com/stage/2020/mar/17/hottest-front-room-seats-the-best-theatre-and-dance-to-watch-online",
        "isHosted":false,
        "pillarId":"pillar/arts",
        "pillarName":"Arts"
      },
      {
        "id":"football/live/2020/jun/27/championship-leeds-united-fulham-preston-cardiff-live",
        "type":"liveblog",
        "sectionId":"football",
        "sectionName":"Football",
        "webPublicationDate":"2020-06-27T11:22:40Z",
        "webTitle":"Championship: Preston v Cardiff, Swansea v Luton and more – live!",
        "webUrl":"https://www.theguardian.com/football/live/2020/jun/27/championship-leeds-united-fulham-preston-cardiff-live",
        "apiUrl":"https://content.guardianapis.com/football/live/2020/jun/27/championship-leeds-united-fulham-preston-cardiff-live",
        "isHosted":false,
        "pillarId":"pillar/sport",
        "pillarName":"Sport"
      },
      {
        "id":"world/live/2020/jun/27/coronavirus-live-news-us-records-biggest-daily-case-rise-as-australia-continues-cluster-testing-blitz-brazil-eu-travel-ban-us",
        "type":"liveblog",
        "sectionId":"world",
        "sectionName":"World news",
        "webPublicationDate":"2020-06-27T11:11:33Z",
        "webTitle":"Coronavirus live news: India passes 500,000 cases as Australian state of Victoria reports surge",
        "webUrl":"https://www.theguardian.com/world/live/2020/jun/27/coronavirus-live-news-us-records-biggest-daily-case-rise-as-australia-continues-cluster-testing-blitz-brazil-eu-travel-ban-us",
        "apiUrl":"https://content.guardianapis.com/world/live/2020/jun/27/coronavirus-live-news-us-records-biggest-daily-case-rise-as-australia-continues-cluster-testing-blitz-brazil-eu-travel-ban-us",
        "isHosted":false,
        "pillarId":"pillar/news",
        "pillarName":"News"
      },
      {
        "id":"world/2020/jun/27/coronavirus-uk-map-the-latest-deaths-and-confirmed-covid-19-cases",
        "type":"article",
        "sectionId":"world",
        "sectionName":"World news",
        "webPublicationDate":"2020-06-27T11:06:17Z",
        "webTitle":"Coronavirus UK map: the latest deaths and confirmed Covid-19 cases",
        "webUrl":"https://www.theguardian.com/world/2020/jun/27/coronavirus-uk-map-the-latest-deaths-and-confirmed-covid-19-cases",
        "apiUrl":"https://content.guardianapis.com/world/2020/jun/27/coronavirus-uk-map-the-latest-deaths-and-confirmed-covid-19-cases",
        "isHosted":false,
        "pillarId":"pillar/news",
        "pillarName":"News"
      },
      {
        "id":"artanddesign/2020/jun/27/milton-glaser-why-the-new-york-graphic-designer-was-so-influential",
        "type":"article",
        "sectionId":"artanddesign",
        "sectionName":"Art and design",
        "webPublicationDate":"2020-06-27T15:16:33Z",
        "webTitle":"Milton Glaser graphic designer dies aged 91 i love ny logo",
        "webUrl":"https://www.theguardian.com/artanddesign/2020/jun/27/milton-glaser-why-the-new-york-graphic-designer-was-so-influential",
        "apiUrl":"https://content.guardianapis.com/artanddesign/2020/jun/27/milton-glaser-why-the-new-york-graphic-designer-was-so-influential",
        "isHosted":false,
        "pillarId":"pillar/arts",
        "pillarName":"Arts"
      },
      {
        "id":"world/2020/jun/27/us-reopening-plans-reverse-quickly-amid-alarming-increase-coronavirus-cases",
        "type":"article",
        "sectionId":"world",
        "sectionName":"World news",
        "webPublicationDate":"2020-06-27T15:11:54Z",
        "webTitle":"US reopening plans reverse quickly amid alarming increase in coronavirus cases",
        "webUrl":"https://www.theguardian.com/world/2020/jun/27/us-reopening-plans-reverse-quickly-amid-alarming-increase-coronavirus-cases",
        "apiUrl":"https://content.guardianapis.com/world/2020/jun/27/us-reopening-plans-reverse-quickly-amid-alarming-increase-coronavirus-cases",
        "isHosted":false,
        "pillarId":"pillar/news",
        "pillarName":"News"
      },
      {
        "id":"uk-news/2020/jun/27/police-find-body-in-search-for-missing-teenager-noah-donohoe",
        "type":"article",
        "sectionId":"uk-news",
        "sectionName":"UK news",
        "webPublicationDate":"2020-06-27T15:02:42Z",
        "webTitle":"Police find body in search for missing teenager Noah Donohoe",
        "webUrl":"https://www.theguardian.com/uk-news/2020/jun/27/police-find-body-in-search-for-missing-teenager-noah-donohoe",
        "apiUrl":"https://content.guardianapis.com/uk-news/2020/jun/27/police-find-body-in-search-for-missing-teenager-noah-donohoe",
        "isHosted":false,
        "pillarId":"pillar/news",
        "pillarName":"News"
      },
      {
        "id":"lifeandstyle/2020/jun/27/home-advantage-three-creatives-share-their-tips-on-home-working",
        "type":"article",
        "sectionId":"lifeandstyle",
        "sectionName":"Life and style",
        "webPublicationDate":"2020-06-27T15:00:05Z",
        "webTitle":"Home advantage: making the most of WFH",
        "webUrl":"https://www.theguardian.com/lifeandstyle/2020/jun/27/home-advantage-three-creatives-share-their-tips-on-home-working",
        "apiUrl":"https://content.guardianapis.com/lifeandstyle/2020/jun/27/home-advantage-three-creatives-share-their-tips-on-home-working",
        "isHosted":false,
        "pillarId":"pillar/lifestyle",
        "pillarName":"Lifestyle"
      },
      {
        "id":"commentisfree/2020/jun/27/is-it-payback-time-for-apple-as-the-eu-goes-after-its-licences-to-print-money",
        "type":"article",
        "sectionId":"commentisfree",
        "sectionName":"Opinion",
        "webPublicationDate":"2020-06-27T15:00:05Z",
        "webTitle":"Is it payback time for Apple as the EU goes after its licences to print money? | John Naughton",
        "webUrl":"https://www.theguardian.com/commentisfree/2020/jun/27/is-it-payback-time-for-apple-as-the-eu-goes-after-its-licences-to-print-money",
        "apiUrl":"https://content.guardianapis.com/commentisfree/2020/jun/27/is-it-payback-time-for-apple-as-the-eu-goes-after-its-licences-to-print-money",
        "isHosted":false,
        "pillarId":"pillar/opinion",
        "pillarName":"Opinion"
      },
      {
        "id":"test",
        "type":"testarticle",
        "sectionId":"commentisfree",
        "sectionName":"Testing",
        "webPublicationDate":"2020-06-27T15:00:05Z",
        "webTitle":"Is this application going to be successful? | Al Sumner",
        "webUrl":"https://www.theguardian.com/commentisfree/2020/jun/27/testing",
        "apiUrl":"https://content.guardianapis.com/commentisfree/2020/jun/27/testing",
        "isHosted":false,
        "pillarId":"pillar/test",
        "pillarName":"Testy"
      }
    ]
  }
}