# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Jest Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test_pull_request:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js Latest Version
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'npm'
    - name: Create an apiKeys.js file
      run: >
        echo "module.exports = { GUARDIAN_API_KEY: '' };" >> apiKeys.js
    - name: Install node packages
      run: npm ci
    - name: Run tests
      run: npm run test
    - name: Run page build
      run: npm run buildOnce
